/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package email.haemmerle.talkplanning

import tornadofx.*

class Talkplanning: App(MyView::class)

class MyView: View() {
    override val root = vbox {
        button("Press me")
        label("Waiting")
    }
}

fun main(args: Array<String>) {
    launch<Talkplanning>(args)
}