/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package email.haemmerle.talkplanning

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = Talkplanning()
        assertNotNull(classUnderTest.toString(), "app should have a greeting")
    }
}
